version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bank_postgres_db
    environment:
      POSTGRES_USER: bank_admin
      POSTGRES_PASSWORD: SecretPassword123!
      POSTGRES_DB: bank_management
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
